---
driver:
  name: vagrant
  network:
  - ["private_network", { ip: "172.16.1.111" }]
  - ["forwarded_port", {guest: 80, host: 80}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[rg::default]

